# Python stubs generated by omniidl from server.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(0,5, __file__)


#
# Start of module "Server"
#
__name__ = "Server"
_0_Server = omniORB.openModule("Server", "server.idl")
_0_Server__POA = omniORB.openModule("Server__POA", "server.idl")


# interface ServerIF
_0_Server._d_ServerIF = (omniORB.tcInternal.tv_objref, "IDL:Server/ServerIF:1.0", "ServerIF")
_0_Server.ServerIF = omniORB.newEmptyClass()
class ServerIF :
    _NP_RepositoryId = _0_Server._d_ServerIF[1]

    def __init__(self):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Server.ServerIF = ServerIF
_0_Server._tc_ServerIF = omniORB.tcInternal.createTypeCode(_0_Server._d_ServerIF)
omniORB.registerType(ServerIF._NP_RepositoryId, _0_Server._d_ServerIF, _0_Server._tc_ServerIF)

# ServerIF operations and attributes
ServerIF._d_recieveLargeString = (((omniORB.tcInternal.tv_string,0), ), (), None)
ServerIF._d_sendLargeString = ((), ((omniORB.tcInternal.tv_string,0), ), None)
ServerIF._d_recieveInt = ((omniORB.tcInternal.tv_short, ), (), None)

# ServerIF object reference
class _objref_ServerIF (CORBA.Object):
    _NP_RepositoryId = ServerIF._NP_RepositoryId

    def __del__(self):
        if _omnipy is not None:
            _omnipy.releaseObjref(self)


    def recieveLargeString(self, *args):
        return _omnipy.invoke(self, "recieveLargeString", _0_Server.ServerIF._d_recieveLargeString, args)

    def sendLargeString(self, *args):
        return _omnipy.invoke(self, "sendLargeString", _0_Server.ServerIF._d_sendLargeString, args)

    def recieveInt(self, *args):
        return _omnipy.invoke(self, "recieveInt", _0_Server.ServerIF._d_recieveInt, args)

    __methods__ = ["recieveLargeString", "sendLargeString", "recieveInt"] + CORBA.Object.__methods__

omniORB.registerObjref(ServerIF._NP_RepositoryId, _objref_ServerIF)
_0_Server._objref_ServerIF = _objref_ServerIF
del ServerIF, _objref_ServerIF

# ServerIF skeleton
__name__ = "Server__POA"
class ServerIF (PortableServer.Servant):
    _NP_RepositoryId = _0_Server.ServerIF._NP_RepositoryId

    def __del__(self):
        if _omnipy is not None:
            _omnipy.releaseObjref(self)

    _omni_op_d = {"recieveLargeString": _0_Server.ServerIF._d_recieveLargeString, "sendLargeString": _0_Server.ServerIF._d_sendLargeString, "recieveInt": _0_Server.ServerIF._d_recieveInt}

ServerIF._omni_skeleton = ServerIF
_0_Server__POA.ServerIF = ServerIF
del ServerIF
__name__ = "Server"

#
# End of module "Server"
#
__name__ = "server_idl"

_exported_modules = ( "Server", )

# The end.
