# Python stubs generated by omniidl from secret_messenger.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(2,0, __file__)


#
# Start of module "messenger"
#
__name__ = "messenger"
_0_messenger = omniORB.openModule("messenger", r"secret_messenger.idl")
_0_messenger__POA = omniORB.openModule("messenger__POA", r"secret_messenger.idl")


# interface SecretMessage
_0_messenger._d_SecretMessage = (omniORB.tcInternal.tv_objref, "IDL:messenger/SecretMessage:1.0", "SecretMessage")
omniORB.typeMapping["IDL:messenger/SecretMessage:1.0"] = _0_messenger._d_SecretMessage
_0_messenger.SecretMessage = omniORB.newEmptyClass()
class SecretMessage :
    _NP_RepositoryId = _0_messenger._d_SecretMessage[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_messenger.SecretMessage = SecretMessage
_0_messenger._tc_SecretMessage = omniORB.tcInternal.createTypeCode(_0_messenger._d_SecretMessage)
omniORB.registerType(SecretMessage._NP_RepositoryId, _0_messenger._d_SecretMessage, _0_messenger._tc_SecretMessage)

# SecretMessage operations and attributes
SecretMessage._d_get_message = ((), ((omniORB.tcInternal.tv_string,0), ), None)

# SecretMessage object reference
class _objref_SecretMessage (CORBA.Object):
    _NP_RepositoryId = SecretMessage._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def get_message(self, *args):
        return _omnipy.invoke(self, "get_message", _0_messenger.SecretMessage._d_get_message, args)

    __methods__ = ["get_message"] + CORBA.Object.__methods__

omniORB.registerObjref(SecretMessage._NP_RepositoryId, _objref_SecretMessage)
_0_messenger._objref_SecretMessage = _objref_SecretMessage
del SecretMessage, _objref_SecretMessage

# SecretMessage skeleton
__name__ = "messenger__POA"
class SecretMessage (PortableServer.Servant):
    _NP_RepositoryId = _0_messenger.SecretMessage._NP_RepositoryId


    _omni_op_d = {"get_message": _0_messenger.SecretMessage._d_get_message}

SecretMessage._omni_skeleton = SecretMessage
_0_messenger__POA.SecretMessage = SecretMessage
del SecretMessage
__name__ = "messenger"

#
# End of module "messenger"
#
__name__ = "secret_messenger_idl"

_exported_modules = ( "messenger", )

# The end.
